---
project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.md"
    - "!README.md"
    - "!LICENSE.md"
  resources:
    - "files/"

execute:
  # Re-render only when source changes
  freeze: auto

bibliography: files/bib/references.bib
csl: files/bib/chicago-author-date.csl
description-meta: "Course on the Economics of Health Care Markets at Emory University"

website:
  title: "Economics of Health Care Markets"
  site-url: "https://econ372f24.classes.ianmccarthyecon.com/"

  twitter-card:
    image: "/files/social-image-f22.png"
    card-style: summary_large_image
    creator: "@ianhealthecon"
    # site: "@andrewheiss"

  open-graph:
    image: "/files/social-image-f22.png"
    locale: en_US

  repo-url: "https://github.com/imccart/econ372-fall2024"

  page-navigation: true

  navbar:
    pinned: true
    background: primary
    right:
      - syllabus.qmd
      - text: "Schedule"
        file: schedule/index.qmd
      - text: "Assignments"
        file: assignments/index.qmd
      - text: "Resources"
        file: resources/index.qmd
      - icon: github
        href: "https://github.com/imccart/econ372-fall2024"
        aria-label: GitHub

  sidebar:
    - title: "Assignments"
      style: "docked"
      background: dark
      contents:
        - assignments/index.qmd
        - assignments/homework1.qmd
        - assignments/homework2.qmd
        - assignments/homework3.qmd
        - assignments/exam1.qmd
        - assignments/project.qmd
  
    - title: "Resources"
      style: "docked"
      background: dark
      contents:
        - resources/index.qmd
        - resources/review1.qmd
        - resources/review2.qmd
        - resources/exam-review1.qmd
        - resources/wksheet1.qmd
        - resources/wksheet2.qmd
        - resources/wksheet3.qmd
        - resources/wksheet4.qmd
        - resources/wksheet5.qmd
        - resources/wksheet6.qmd
        - resources/wksheet7.qmd
        - resources/wksheet8.qmd
        - resources/wksheet9.qmd
        - resources/wksheet10.qmd
        - resources/wksheet11.qmd
        - resources/wksheet12.qmd


  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} 2024 by Ian McCarthy<br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub](https://github.com/imccart/econ372-fall2024)


format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai
    grid:
      sidebar-width: 350px