---
title: "Homework 2"
format: html
#format:
#  pdf: default
---

## Instructions
This is our second homework assignment of the semester. It covers questions related to physician treatment decisions and asymmetric information. Before you get started, I want to acknowledge that the data you're using for this assignment might be more than you're accustomed to at this stage of your college career. That's OK! We are here to help.

Why am I asking you to work with such a seemingly large dataset (aside: it's not really that big of a dataset, but it probably feels that way now):

- Experience with most common public data on physician behaviors and utilization
- See (with real data) physician response to payment changes (Q4)
- See (with real data) potential budget implications of payment changes (Q5, Part 3)
- Predict behaviors using the intuition from our physician agency models

Homework 2 is due by **midnight on Friday, October 18**.


## Theory Questions
1. Assume a physician is operating with the standard profit function, $\pi = (p-c)x$, where $c$ reflects a constant marginal cost of production, $x$ denotes quantity of healthcare provided, and $p$ denotes the price per unit of healthcare provided. Assume also that patients receive some total benefit from care received, reflected by the equation $B(x)=10x - (1/2)x^{2}$. Patients must pay the full price, $p$, of any care received, so that the net benefit of care to the patient is then $B(x)-px$ (their total benefit less their costs). Finally, assume that the best outside option for the patient yields a net benefit of 8.

    + If the patient were to choose $x$ to maximize their net benefit, what level of $x$ would they choose?
    
    + Find the physician's profit maximizing choice of quantity, $x$. You need to solve this as a function of $c$.
    
    + At a marginal cost of $c=2$, find the physician's optimal price, $p$.
    
    + Compare the physician's profit maximizing choice of $x$ to the patient's optimal choice of $x$. Are these the same? Why or why not?


2. Assume now that the physician can affect the number of their patients through their influence on the net benefit (NB) provided to patients. Assume also that the physician faces a fixed price paid by the insurer, denoted $p_{s}$, along with a capitated payment per patient, $R$, and that the patient faces a price of \$0, $p_{d}=0$. In this extension, the physician's goal is to choose $x$ so as to maximize profit, $$\pi = n\left(NB\right) \left[R + (p_{s}-c)x \right].$$ Finally, assume the functional forms $n(NB)=\sqrt{NB}$ and $B(x)=12x-x^{2}$.

    + Find the patient's optimal level of $x$.
    
    + Assuming that the physician makes \$1 on each quantity of care provided ($p_{s}-c=1$), find the value of the capitated payment, $R$, such that overtreatment is minimized. Please assume that $x$ can only take discrete values, so that the minimum amount of overtreatment is 1 "unit of care" per patient.
    
    + Assuming that the physician loses \$1 on each quantity of care provided ($p_{s}-c=-1$), find the value of the capitated payment, $R$, such that undertreatment is minimized. Again, assume that $x$ can only take discrete values, so that the minimum amount of undertreatment is 1 "unit of care" per patient.
    
    + Which scenario (minimizing overtreatment or undertreatment) is better for the physician's profit.


3. Two physicians, Physician 1 and Physician 2, are considering the adoption of a new medical treatment for a specific condition. Both physicians have access to the same observational data from a clinical trial in which 100 patients were treated with the new treatment, and 20 out of 100 patients showed improvement. The physicians, however, have different prior beliefs about the treatment's effectiveness.

   - Physician 1's Prior: $Beta(\alpha = 1, \beta = 1)$ distribution (Diffuse or Uniform prior).
   - Physician 2's Prior: $Beta(\alpha = 1, \beta = 30)$ distribution (Strong negative prior).

     + Calculate the updated belief of Physician 1 regarding the effectiveness of the new treatment. Express this updated belief as the mean of the posterior distribution.

     + Calculate the updated belief of Physician 2 regarding the effectiveness of the new treatment. Express this updated belief as the mean of the posterior distribution.

     + Compare the updated beliefs of Physician 1 and Physician 2. Interpret how their different prior beliefs have influenced their updated beliefs despite having access to the same observational data. Discuss the impact of prior strength on the updating process.

     + Based on the calculated updated beliefs and your understanding of Bayesian inference, assess which physician is likely to adopt the new treatment more quickly. Provide a reasoned explanation for your prediction, considering the interplay between prior beliefs, observational data, and the updating process.


## Empirical Questions

4. In January 2014, CMS reduced it's payments to physicians for epidural steroidal injections (CPT codes 62310, 62311, 62318, and 62319). The reduction was part of an effort to adjust "potentially misvalued services," in which CMS lowered the payment rates back to 2013 levels. CMS subsequently increased the payment levels in 2015. Talk about whiplash! For this question, we're going to use the Medicare Provider Utilization and Payment Data from 2013 through 2015 to see how these payment changes may have affected the frequency of epidural steroidal injections. These data are available on our OneDrive folder for homework 2, the link to which is on Canvas. The data are available as an R data set, `hwk2_data_q4.Rdata`, or as a tab-delimited text file `hwk2_data_q4.txt`. Take a look at the data in your favorite software, and answer the following questions:

   + How many unique physicians administered at least one epidural steroidal injection in 2013?
    
   + Among those physicians, what was the average number of injections in each year (2013 through 2015)? Use a graph to support your answer.
    
   + Among physicians with some injections in both 2013 and 2014, identify the physicians with the 10 largest reductions in injections from 2013 to 2014 (i.e., I want to see the physicians with the largest reductions, but exclude physicians that dropped to 0).

   + For the physicians identified in part 3, plot the number of injections for each physician over time (scatter plot with the count of injections on the vertical axis and year on the horizontal axis).


::: {.callout-tip collapse="true"}
For part 3, consider the following strategies:

   - Pivot table
     - hlookup/vlookup in Excel, pivot_wider in R
   - Create individual 2013 and 2014 datasets, and join the data
     - hlookup in Excel, inner_join in R
   - Create new variable (2014 count - 2013 count)
   - Take smallest 10 values (largest negatives)
     - hlookup/vlookup in Excel
     - slice in R
:::
    


5. In January 2021, CMS changed its physician fee schedule, instituting relatively large increases for "Evaluation and Management" (E&M, or just office visits) codes. **But**, due to budget neutrality requirements, such an increase required an offset for other services. Therefore, CMS also lowered the overall "conversion factor". This made more expensive services in 2020 relatively less profitable, while payments for otherwise less expensive services were less affected (E&M services, of course, actually increased in payment rate). For this question, we're going to again work with the Medicare Provider Utilization and Payment Data (`hwk2_data_q5.Rdata` as an R data set or `hwk2_data_q5.txt` as a tab-delimited text file). We'll focus only on physicians in Georgia because the full data is a little too much to manage for this assignment. Please be sure to take a look at the primer, available [here](cms-em-2021-finalrule.pdf), for more details about the policy and payment changes. Then answer the following questions:

    + Identify a set of HCPCS codes that capture physician office visits. Do some internet digging first, just to see if you can find the codes that way. Ultimately, the best strategy is probably to identify the relevant codes based on the observed descriptions in the data.
    
    + Identify the physicians with the most (top 10) E&M visits in 2020.
    
    + How much would these physicians from part B (the top 10 physicians) stand to gain from the increased RVU rate? Show your results in a table. You can see the percentage increases from the CMS Final Rule Discussion document available [here](cms-em-2021-finalrule.pdf).
    
    + In the context of physician agency, what might you predict will happen to utilization of more expensive services after the 2021 fee schedule update?

::: {.callout-tip collapse="true"}
For part 3, consider the following:

   - Calculate total payments (avg_payment*count)
   - Apply % increase from 2020 to 2021 to find new payment
:::
