---
title: "Homework 3"
format: html
#format:
#  pdf: default
---

## Instructions
This is our third and final homework assignment of the semester. It covers questions related to hospital pricing and competition. Homework 3 is due by **midnight on Friday, November 14**.

## Theory Questions
1. Consider a for-profit practice facing the following demand and cost curves: $p=75-\frac{1}{2}q$ for private insurance patients and $c(q)=\frac{1}{4}q^{2}$.

    + Find the profit-maximizing number of patients and price?
    
    + Now assume that there is also a public market (e.g., Medicaid) where the price is set to $\bar{p}=\$40$ for each patient. Calculate the total number of patients that will be seen by this practice, and report the split between private and public patients. Also report the private price for this provider.
    
    + Medicaid is considering lowering their payments to $30 per visit. Repeat part (b) with this new public price.

    + Suppose the practice has a binding capactiy constraint of $q_{max}=70$ (i.e., they can't see any more than 70 patients total). Resolve part (b) and discuss (in 2-3 sentences) how this capacity constraint changes the incidence of a cut from $\bar{p}=40$ to $\bar{p}=30$.

2. Suppose Town A and Town B each have four hospitals. The tables below provide the bed size and output of each hospital. Use this information to answer the following questions:

    + What is the Hirfindahl-Hirschman Index (HHI) for each town if we define market share as the share of total beds versus total discharges?
    
    + Which market (Town A or Town B) is more concentrated under each definition? Do the rankings differ? Explain briefly.
  
    + Suppose Hospital C and D are proposing a merger in Town B. Recompute HHI using discharges under this hypothetical merger. By how much does HHI change? Would the merger trigger antitrust scrutiny under DOJ/FTC thresholds?


<b>Town A</b><br>

 Hospital     | Bed Size | Discharges
 -------------| -------- | ---------
 A            | 250      | 8,000
 B            | 250      | 7,300
 C            | 250      | 6,400
 D            | 250      | 5,400
 
<br>
<b>Town B</b><br>

 Hospital     | Bed Size | Discharges
 -------------| -------- | ---------
 A            | 100      | 2,200
 B            |  50      | 1,100
 C            | 500      | 6,000
 D            | 350      | 5,000


<br> 



3. From our Nash bargaining framework, assume that two agents are negotiating over how best to divide their quantity of good $x$. Normalize the value of the good to 1, and assume that player 1 receives $x$ and player 2 receives $1-x$. Further assume that player 1 has some "bargaining power" denoted by $\alpha$ and player 2 has some bargaining power denoted by $\beta$. In this setup, the Nash bargaining solution is one that maximizes $(u_{1} - t_{1})^{\alpha}(u_{2}-t_{2})^{\beta}$, where $u_{1}$ and $u_{2}$ denote the payoffs under agreement and $t_{1}$ and $t_{2}$ denote the payoffs without agreement. 

    + Assume that, if the players fail to reach an agreement, they each receive utility of 0, so that $t_{1}=t_{2}=0$. Find the symmetric Nash bargaining solution to this game and explain how the solution depends on $\alpha$ and $\beta$.
    
    + Assume that $\alpha$ and $\beta$ measure risk aversion among the players. What can you conclude about the outcome of bargaining in the case of one risk neutral (e.g., $\alpha=1$) and one risk averse agent (e.g., $\beta<1$) ?
    
    + Assume instead that $\alpha=\beta$ and that player 2 now has some positive payoff, $a$, regardless of the value of $x$. In other words, $t_{2}=a$, while $t_{1}$ is still 0. What is the bargaining solution in this game? Briefly explain how it depends on the value of $a$.
    
    + Suppose player 1 is a hospital and player 2 is a private insurer. The "players" are bargaining over the division of a surplus normalized to size 1 (e.g., revenue from patients). Interpret $\alpha$, $\beta$, and $a$ in this context. Give one example of a real-life factor that might increase the hospital's outside option, and explain how it would affect the negotiated division.


## Empirical Questions
4. Let's study how our assessment of hospital markets and competitiveness changes depending on our definition of a market. For these questions, we're going to work with the hospital data available on our *OneDrive* folder. I created this dataset from the Hospital Cost Report Information System (HCRIS) and the Hospital Service Area Files. In these data, markets are defined in 3 ways: zip code, HRR, and my own "market" calculation using something called a "community detection" algorithm. Throughout this homework, I'll define the market share of hospital $i$ in market $m$ at year $t$ as: $s_{imt} = \frac{q_{imt}}{\sum_{j} q_{jmt}}$, where $q$ denotes discharges.

    + Calculate hospital market shares using zip code as your definition of a market. Then compute the HHI for each zip code and year. Finally, provide a graph of the average HHI over time ("average" meaning a simple unweighted average of HHIs across zip codes in a given year).

    + Repeat part (a) using HRR as your measure of the market.

    + Repeat part (a) using the pre-determined "markets" based on the community detection algorithm.
    
    + Explain the differences in your results from parts (a)-(c). How does your assessment of the concentration of hospital markets change depending on the geographic definition of the market?

    + Recreate part (c) using the maximum market share, $s_{mt}^{max}=\max_{i} s_{imt}$, instead of HHI. In other words, computer $s_{mt}^{max}$, average those values across markets for each year, and plot the results. How does your assessment of the competitiveness of hospital markets change, if at all?
    
5. Now let's think about hospital prices. To do this, we're going to summarize some pricing data and see how prices correlate with market structure. We'll use the same hospital data from question 4, focusing on the community detection measure of markets.

    + Calculate the average price for each year and show your results in a graph.
    
    + Identify markets that are monopolies or duopoloies (i.e., exactly one or two hospitals in a market-year) and those that are "competitive" (which we can define as at least 4 hospitals in a market-year). Show in a graph the count of all such markets over time.
    
    + Calculate the average price in each year among the markets in part (b). Show your results in a table or a figure. How do these average prices compare?

    + Repeat part (c) after first limiting to markets with between 10,000 and 50,000 total discharges per year. Briefly explain any differences in your results and why such a limit on market size (i.e., total discharges) might matter.